fix: Cypher trig functions can't handle zero
Cypher trigonometric functions can't handle input values of zero.

The problem is with `FunctionCallJsonb` and the way it interacts with
`jsonb_to_datum`. `FunctionCallJsonb` calls `jsonb_to_datum` and if the
returned value is 0, it exits with messages like -

ERROR: radians(): number is expected but 0
ERROR: sin(): number is expected but 0

The problem is that `jsonb_to_datum` returns a 0 for failure but it can
also return a 0 for a valid value - zero - like from the FLOAT8OID case.

The fix is to push down the error detection to `jsonb_to_datum`,
allowing valid zero values to be passed through while still addressing
errors.

Add a regression test for this.